import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost/opencart/');
    await page.getByRole('textbox', { name: 'Search' }).click();
    await page.getByRole('textbox', { name: 'Search' }).fill('macbook');
    await page.locator('#search').getByRole('button').click();
    await page.getByRole('link', { name: 'MacBook' }).first().click();
    await page.getByRole('button', { name: 'Add to Cart' }).click();
    await page.getByRole('button', { name: ' 1 item(s) - $' }).click();
    await page.getByRole('button', { name: ' 1 item(s) - $' }).click();
    await page.getByRole('button', { name: ' 1 item(s) - $' }).click();
    await page.getByRole('link', { name: ' View Cart' }).click();
    await page.locator('input[name="quantity[96]"]').click();
    await page.locator('input[name="quantity[96]"]').fill('3');
    await page.getByRole('button').nth(3).click();
    await page.getByRole('link', { name: 'Checkout', exact: true }).click();
    await page.getByText('Guest Checkout').click();
    await page.getByRole('button', { name: 'Continue' }).click();
    await page.getByRole('textbox', { name: '* First Name' }).click();
    await page.getByRole('textbox', { name: '* First Name' }).fill('Xia');
    await page.getByRole('textbox', { name: '* Last Name' }).click();
    await page.getByRole('textbox', { name: '* Last Name' }).fill('Xia');
    await page.getByRole('textbox', { name: '* E-Mail' }).click();
    await page.getByRole('textbox', { name: '* E-Mail' }).fill('user2@gmail.com');
    await page.getByRole('textbox', { name: '* Telephone' }).click();
    await page.getByRole('textbox', { name: '* Telephone' }).fill('012345343');
    await page.getByRole('textbox', { name: '* Address' }).click();
    await page.getByRole('textbox', { name: '* Address' }).fill('Saint Street');
    await page.getByRole('textbox', { name: '* City' }).click();
    await page.getByRole('textbox', { name: '* City' }).fill('Berlin');
    await page.getByRole('textbox', { name: '* Post Code' }).click();
    await page.getByRole('textbox', { name: '* Post Code' }).fill('11232');
    await page.getByLabel('Region / State').selectOption('3513');
    await page.getByRole('button', { name: 'Continue' }).click();
});